*Data-Types in NumPy Arrays*

Installing NumPy

In [2]:
%pip install numpy

Checking numpy version

In [3]:
import numpy as np

np.__version__

'2.0.2'

Numpy 1d, 2d, and 3d array

- 1d

In [4]:
ad1 = np.array([1,2,3])
ad1

array([1, 2, 3])

In [6]:
ad1.shape

(3,)

In [7]:
ad1.size

3

In [8]:
len(ad1)

3

- 2d

In [11]:
ad2 = np.array([[1,2,3],[4,5,6]])
ad2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ad2.size

6

In [13]:
ad2.shape

(2, 3)

In [14]:
len(ad2)

2

- 3d

In [15]:
ad3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]
    ]
)
ad3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
ad3.size

18

In [17]:
ad3.shape

(2, 3, 3)

In [18]:
len(ad3)

2

Supported data types in numpy

In [19]:
# Numpy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.

In [20]:
np.array([1,2,3])

array([1, 2, 3])

In [21]:
np.array([1,2,3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [22]:
np.array([1,2,3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [23]:
np.array([True, False, True], dtype=np.bool)

array([ True, False,  True])

In [24]:
np.array([True, False, True], dtype=np.bool_)

array([ True, False,  True])

In [25]:
np.array([True, False, True], dtype=np.int32)

array([1, 0, 1], dtype=int32)

In [26]:
np.array(['apple', 'ArithmeticError'])

array(['apple', 'ArithmeticError'], dtype='<U15')

In [27]:
np.array(['apple', 'ArithmeticError'], dtype='U10')

array(['apple', 'Arithmetic'], dtype='<U10')

In [28]:
np.array(['apple', 'ArithmeticError'], dtype='U5')

array(['apple', 'Arith'], dtype='<U5')

In [29]:
np.array([1,2,'3'])

array(['1', '2', '3'], dtype='<U21')

In [30]:
np.array([1,2,'3'], dtype=np.int32)

array([1, 2, 3], dtype=int32)

Record array or structured array
- Structured arrays in numpy are homogeneous at the array level (each element has the same layout).
- We can specify a type and, optionally, a name on a per-column basis. This makes sorting and filtering even more powerful, and it can feel similar to working with data in Excel, CSVs, or relational databases.

In [32]:
records = [
    ("aman", 25, 3.5),
    ("vishnu", 30, 4.0),
    ("sneha", 22, 3.8),
    ("rohit", 28, 4.2)
]
records

[('aman', 25, 3.5),
 ('vishnu', 30, 4.0),
 ('sneha', 22, 3.8),
 ('rohit', 28, 4.2)]

In [34]:
data = np.array(records)
data

array([['aman', '25', '3.5'],
       ['vishnu', '30', '4.0'],
       ['sneha', '22', '3.8'],
       ['rohit', '28', '4.2']], dtype='<U32')

In [35]:
data = np.array(records, dtype=[('name', 'U15'), ('age', 'int32'), ('gpa', 'float32')])
data

array([('aman', 25, 3.5), ('vishnu', 30, 4. ), ('sneha', 22, 3.8),
       ('rohit', 28, 4.2)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('gpa', '<f4')])

In [36]:
data = np.array(records, dtype=[('name', 'U15'), ('age', int), ('gpa', float)])
data

array([('aman', 25, 3.5), ('vishnu', 30, 4. ), ('sneha', 22, 3.8),
       ('rohit', 28, 4.2)],
      dtype=[('name', '<U15'), ('age', '<i8'), ('gpa', '<f8')])

You can specify the dtype(data type) in several equipment ways.
1. Using numpy type strings (compact format) - [ ("name", "U15"), ("age", "14"), ("marks", "14")]
2. Using numpy type objects (recommended) - [("name", np.unicode_), ("age", np. int32), ("marks", np.int32)]
3. Mixing python build-in types and numpy types - [ ( "name", str), ("age", int), ("marks", np.int32)]

In [37]:
data[0]

np.void(('aman', 25, 3.5), dtype=[('name', '<U15'), ('age', '<i8'), ('gpa', '<f8')])

In [38]:
print(data[0])

('aman', 25, 3.5)


In [39]:
data["name"]

array(['aman', 'vishnu', 'sneha', 'rohit'], dtype='<U15')

By default, NumPy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.
- Homogeneous arrays allow:
1. Vectorized operations
2. Efficient memory layout (contiguous blocks)
3. Fast computations using C under the hood
- NumPy is designed for arrays of fixed-size elements — typically numerical data types (integers, floats), but also supports strings, booleans, dates, and custom structured types.
- All elements in a NumPy array share the same data type ( dtype ).
- The data is stored in a contiguous block of memory for efficiency.

- It can support heterogeneous types using object arrays or structured dtypes, but these lose most performance benefits.