Numpy-3 : Ways to Create Numpy Arrays

In [1]:
import numpy as np

From built-in python containers (Lists, Tuples etc)

In [3]:
# using list
np. array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# using tuples
np.array( (1,2,3,4))

array([1, 2, 3, 4])

Upcasting in Numpy
- Upcasting in NumPy refers to the automatic conversion of data types when performing operations involving arrays of different types, so that no data is lost and the resuable has a compatible type that can hold all input values.

In [5]:
np.array([1,2.5,3,4])

array([1. , 2.5, 3. , 4. ])

Two Dimensional numpy array

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

Minimum dimensions 2

In [7]:
np.array([[[1,2,3,4]]], ndmin = 2)

array([[[1, 2, 3, 4]]])

dtype

In [8]:
np.array([1,'1',3,4], dtype = complex)

array([1.+0.j, 1.+0.j, 3.+0.j, 4.+0.j])

data consisting of more than one Data-type

In [10]:
x = np. array([(1,2), (3,4.2) ],dtype=[( 'a', 'i4'), ('b',np. float32)])
x

array([(1, 2. ), (3, 4.2)], dtype=[('a', '<i4'), ('b', '<f4')])

In [11]:
x['a']

array([1, 3], dtype=int32)

In [12]:
x['b']

array([2. , 4.2], dtype=float32)